version: '2'
services:
    example.com:
        ports:
            -   80:8080
    developer:
        build: ./compose/developer
        container_name: dev
        volumes:
            -   ./example.com:/usr/src/app:rw
        working_dir: /usr/src/app
        ports:
            -   3000:3000
            -   3001:3001
        networks:
            - frontend
